inc42_warehouse:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: bigquery-296406
      keyfile: /secrets/bq-service-account.json
      dataset: silver
      location: asia-south1
      threads: 4
